markdown: kramdown
highlighter: pygments

permalink:   pretty

title:       'PHP.ug-Blog'
tagline:     'One home for one community'
description: '<p>Ever wanted to know where the next group of PHP-Enthusiasts is near you?
                          Have a look at the map at <a href="http://php.ug">PHP.ug</a> - The php.ug project aims to provide
                          an up-to-date resource for finding PHP-Usergroups and other
                          community-resources around the globe. See what and who is next to you.
                      </p>
                      <p>
                          For that we maintain the list of active usergroups that you can
                          also find on <a href="http://PHP.net/ug">php.net/ug</a>
                      </p>'
url:         http://php-ug.github.io/

paginate:    5
baseurl:     /php.ug

author:
  name:      'Andreas Heigl'
  url:       http://andreas.heigl.org
  email:     andreas@heigl.org

version:     1.0.0
github:
  repo:      https://github.com/php-ug/php.ug


tracking:    '<!-- Piwik -->
    <script type="text/javascript">
        var _paq = _paq || [];
        _paq.push(["trackPageView"]);
        _paq.push(["enableLinkTracking"]);
        (function() {
            var u=(("https:" == document.location.protocol) ? "https" : "http") + "://piwik.heigl.org/";
            _paq.push(["setTrackerUrl", u+"piwik.php"]);
            _paq.push(["setSiteId", 4]);
            var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
            g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
        })();
    </script>
    <noscript><p><img src="http://piwik.heigl.org/piwik.php?idsite=4" style="border:0;" alt="" /></p></noscript>
    <!-- End Piwik Code -->'
